sudo: false

language: python

python:
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -e .[test]

script: python setup.py test --addopts "--verbose $PYTEST_ADDOPTS"
